 name: Prius Monitor

  on:
    schedule:
      - cron: '*/30 * * * *'
    workflow_dispatch:

  jobs:
    monitor:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install playwright beautifulsoup4 python-dotenv requests
          playwright install chromium

      - name: Run Prius monitor
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          python cloud_monitor.py
